---
- name: "firewalld █ Add services to firewall's {{ log_server_firewall_zone | default('public',true) }} zone"
  firewalld:
    zone: "{{ log_server_firewall_zone | default('public',true) }}"
    service: "{{ item }}"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  when:
    - ansible_facts.os_family == "RedHat"
    - ep_firewall | default(false) | bool
  loop: "{{ j2_role_variables['firewall_services_to_add'] }}"
  tags:
    - firewall

- name: "firewalld █ Add custom port to firewall's {{ log_server_firewall_zone | default('public',true) }} zone"
  firewalld:
    zone: "{{ log_server_firewall_zone | default('public',true) }}"
    port: "{{ log_server_port }}/tcp"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  when:
    - ansible_facts.os_family == "RedHat"
    - ep_firewall | default(false) | bool
  tags:
    - firewall

- name: "package █ Install {{ j2_role_variables['packages_to_install'] | join(' ') }}"
  package:
    name: "{{ j2_role_variables['packages_to_install'] }}"
    state: present
  tags:
    - package

- name: file █ Create /var/log/rsyslog directory
  file:  # noqa 208
    path: /var/log/rsyslog
    setype: var_log_t
    state: directory
    recurse: yes
  when:
    - ansible_facts.os_family == "RedHat"
    - ansible_facts.selinux.status == "enabled"

- name: "template █ Generate {{ log_server_rsyslog_conf_path }}"
  template:
    src: rsyslog.conf.j2
    dest: "{{ log_server_rsyslog_conf_path }}"
    owner: root
    group: root
    mode: 0644
  notify: service █ Restart rsyslog service
  tags:
    - template

- name: seport █ Allow syslog port into SELinux
  seport:
    ports: "{{ log_server_port }}"
    proto: "{{ item }}"
    setype: syslogd_port_t
    state: present
  when:
    - ansible_facts.os_family == "RedHat"
    - ansible_facts.selinux.status == "enabled"
  loop:
    - tcp
    - udp
  notify: service █ Restart rsyslog service

- name: "template █ Generate /etc/logrotate.d/rsyslog"
  template:
    src: rsyslog_logrotate.j2
    dest: /etc/logrotate.d/rsyslog
    owner: root
    group: root
    mode: 0644
  notify: service █ Restart rsyslog service
  tags:
    - template

- name: lineinfile █ Configure logrotate to use xz
  lineinfile:
    path: /etc/logrotate.conf
    regexp: "{{ item }}"
    line: "{{ item }}"
  loop:
    - compresscmd /usr/bin/xz
    - uncompresscmd /usr/bin/unxz
    - compressext .xz
  notify: service █ Restart rsyslog service
  tags:
    - template

- meta: flush_handlers

- name: "service █ Manage {{ j2_role_variables['services_to_start'] | join(' ') }} state"
  service:
    name: "{{ item }}"
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  loop: "{{ j2_role_variables['services_to_start'] }}"
  tags:
    - service
