---
- name: Converge
  hosts: all
  serial: 3

  vars:
    # Start the services by default
    start_services: true
    enable_services: true
    icebergs_system: false
    networks:
      ice1-1:
        subnet: 10.11.0.0
        prefix: 16
        services_ip:
          time_ip: 10.11.0.1
      ice2-1:
        subnet: 10.12.0.0
        prefix: 16
        services_ip:
          time_ip: ['10.12.0.1', '10.12.0.2']
    time_zone: Europe/Paris
    j2_role_variables: "{{ vars[role_name + '_' + ansible_facts.distribution + '_' + ansible_facts.distribution_version] | default(vars[role_name + '_' + ansible_facts.distribution + '_' + ansible_facts.distribution_major_version]) | default(vars[role_name + '_' + ansible_facts.distribution]) | default(vars[role_name + '_' + ansible_facts.os_family + '_' + ansible_facts.distribution_version]) | default(vars[role_name + '_' + ansible_facts.os_family + '_' + ansible_facts.distribution_major_version]) | default(vars[role_name + '_' + ansible_facts.os_family]) }}"

  tasks:
    - name: "Include time for servers"
      include_role:
        name: "time"
