---
- name: "package █ Install {{ j2_role_variables['packages_to_install'] | join(' ') }} packages"
  package:
    name: "{{ j2_role_variables['packages_to_install'] }}"
    state: present
  tags:
    - package

- name: "service █ Manage {{ j2_role_variables['services_to_start'] | join(' ') }} state"
  service:
    name: "{{ item }}"
    enabled: "{{ (ep_firewall | bool) | ternary('yes','no') }}"
    state: "{{ (ep_firewall | bool) | ternary('started', 'stopped') }}"
  loop: "{{ j2_role_variables['services_to_start'] }}"
  tags:
    - service

- name: "include_tasks ░ Configure firewall: {{ ansible_facts.os_family }}"
  include_tasks: "{{ ansible_facts.os_family }}.yml"
  when: ep_firewall
  tags:
    - internal
