---
log_server_RedHat_7:
  packages_to_install:
    - rsyslog
    - logrotate
    - xz
    - libselinux-python
    - policycoreutils-python
  services_to_start:
    - rsyslog
  firewall_services_to_add:
    - syslog
    - rsh # 514/tcp
