---
- name: Converge
  hosts: all

  vars:
    enable_services: true
    start_services: true
    j2_node_main_network: en0
    networks:
      en0:
        services_ip:
          log_ip: 127.0.0.1
    j2_role_variables: "{{ vars[role_name + '_' + ansible_facts.distribution + '_' + ansible_facts.distribution_version] | default(vars[role_name + '_' + ansible_facts.distribution + '_' + ansible_facts.distribution_major_version]) | default(vars[role_name + '_' + ansible_facts.distribution]) | default(vars[role_name + '_' + ansible_facts.os_family + '_' + ansible_facts.distribution_version]) | default(vars[role_name + '_' + ansible_facts.os_family + '_' + ansible_facts.distribution_major_version]) | default(vars[role_name + '_' + ansible_facts.os_family]) }}"

  tasks:
    - name: "Include log_client"
      include_role:
        name: "log_client"
