---

- name: package <|> Install httpd and haproxy
  ansible.builtin.package:
    name:
      - httpd
      - haproxy
    state: present
  tags:
    - package

- name: lineinfile <|> Disable default listen on all interfaces
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen 80'
    line: '#Listen 80'
  notify: service <|> Restart http server
  when: haproxy_mode == 'http'

- name: template <|> Set http server ips and ports to listen to
  ansible.builtin.template:
    src: listen.conf.j2
    dest: /etc/httpd/conf.d/listen.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - template
  notify: service <|> Restart http server
  when: haproxy_mode == 'http'

- name: template <|> Configure haproxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  tags:
    - template
  notify: service <|> Restart haproxy server

- name: meta <|> Run handler tasks to restart services
  meta: flush_handlers

- name: service <|> Manage httpd service
  ansible.builtin.service:
    name: httpd
    enabled: yes
    state: started
  tags:
    - service
  when: haproxy_mode == 'http'

- name: service <|> Manage haproxy service
  ansible.builtin.service:
    name: haproxy
    enabled: yes
    state: started
  tags:
    - service
