---
- name: Converge
  hosts: all

  vars:
    management_networks_naming: "ice"
    external_dns: []
    networks:
      ice1-1:
        subnet: 10.10.0.0
        prefix: 16
        netmask: 255.255.0.0
        broadcast: 10.10.255.255
        is_in_dns: true
        services_ip:
          dns_ip: 10.10.0.1
    domain_name: example.com
    start_services: false
    enable_services: false
    j2_role_variables: "{{ vars[role_name + '_' + ansible_facts.distribution + '_' + ansible_facts.distribution_version] | default(vars[role_name + '_' + ansible_facts.distribution + '_' + ansible_facts.distribution_major_version]) | default(vars[role_name + '_' + ansible_facts.distribution]) | default(vars[role_name + '_' + ansible_facts.os_family + '_' + ansible_facts.distribution_version]) | default(vars[role_name + '_' + ansible_facts.os_family + '_' + ansible_facts.distribution_major_version]) | default(vars[role_name + '_' + ansible_facts.os_family]) }}"

  tasks:
    - name: "Include dns_server"
      include_role:
        name: "dns_server"
