---

- name: firewalld █ "Add services to firewall's {{ j2_role_variables['firewall_zone'] | default('public') }} zone"
  firewalld:
    zone: "{{ j2_role_variables['firewall_zone'] | default('public') }}"
    service: "{{ item }}"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  when:
    - ansible_facts.os_family == "RedHat"
    - ep_firewall | default(false) | bool
  loop: "{{ j2_role_variables['firewall_services_to_add'] }}"
  tags:
    - firewall

- name: "package █ Install {{ j2_role_variables['packages_to_install'] | join(' ') }} packages"
  package:
    name: "{{ j2_role_variables['packages_to_install'] }}"
    state: present
  tags:
    - package

- name: "service █ Manage {{ j2_role_variables['services_to_start'] | join(' ') }} services state"
  service:
    name: "{{ item }}"
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  loop: "{{ j2_role_variables['services_to_start'] }}"
  tags:
    - service
