- name: package █ Install clustershell package
  package:
    name: clustershell
    state: present
  tags:
    - always

- name: template █ Generate /etc/clustershell/groups.d/local.cfg
  template:
    src: local.cfg.j2
    dest: /etc/clustershell/groups.d/local.cfg
    owner: root
    group: root
    mode: 0644
  tags:
    - template
