---

- name: service <|> Restart keepalived server
  ansible.builtin.service:
    name: keepalived
    state: restarted
  when:
    - "'service' not in ansible_skip_tags"
    - (start_services | bool)
